<a href="https://colab.research.google.com/github/Vineela-Kandru/ML_Homework_Projects/blob/main/Homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

**Question 1: Version of Pandas**

In [2]:
print('pandas version:', pd.__version__)


pandas version: 1.5.3


In [3]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df.ocean_proximity

0        NEAR BAY
1        NEAR BAY
2        NEAR BAY
3        NEAR BAY
4        NEAR BAY
           ...   
20635      INLAND
20636      INLAND
20637      INLAND
20638      INLAND
20639      INLAND
Name: ocean_proximity, Length: 20640, dtype: object

In [6]:
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

**Question 2: Number of columns in the dataset**

In [7]:
df.shape

(20640, 10)

In [8]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [9]:
df.index

RangeIndex(start=0, stop=20640, step=1)

**Question 3: Select columns with missing data**

In [10]:
mvc = df.isnull().sum()

print(mvc)

print('\n')

print('columns with missing data:', mvc[mvc > 0].index.tolist())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


columns with missing data: ['total_bedrooms']


**Question 4: Number of unique values in the 'ocean_proximity' column**

In [11]:
print('no. of unique values in the ocean_proximity column:' ,df.ocean_proximity.nunique())

no. of unique values in the ocean_proximity column: 5


In [12]:
df['ocean_proximity'].unique().tolist()

['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND']

**Question 5: Average value of the 'median_house_value' for the houses near the bay**

In [13]:
df1 = (df[df['ocean_proximity'] == 'NEAR BAY'])

print(' Average value of the "median_house_value" for the houses near the bay:',df1.median_house_value.mean())

 Average value of the "median_house_value" for the houses near the bay: 259212.31179039303


**Question 6: Has the mean value changed after filling missing values?**

In [14]:
print('Mean value before filling missing values:',df.total_bedrooms.mean())

Mean value before filling missing values: 537.8705525375618


In [15]:
#filling missing values with mean of the total_bedrooms column

df3 = df.fillna(df['total_bedrooms'].mean())

#checking the dataset for missing values

filled_values = df3.isna().sum()

In [16]:
#finding the mean after filling missing values

print('Mean value after filling missing values:',df3.total_bedrooms.mean())

Mean value after filling missing values: 537.8705525375617


**Questions 7: Value of the last element of w**

In [17]:
island = (df[df['ocean_proximity'] == 'ISLAND'])

In [25]:
#selecting housing_median_age, total_rooms, total_bedrooms columns only

island = island[['housing_median_age','total_rooms','total_bedrooms']]

print(island)

      housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0


In [27]:
#numpy array

X = island.values

print(X)


[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [20]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Xtranspose = X.T

print(Xtranspose)

XTX = np.dot(X.T, X)

print('\n')

print(XTX)

[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]


[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [28]:
#Compute the inverse of XTX.

inverse = np.linalg.inv(XTX)

In [22]:
#Create an array y with values [950, 1300, 800, 1000, 1300].

y = [950, 1300, 800, 1000, 1300]

In [23]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w = np.dot(np.dot(inverse, Xtranspose), y)

print(w)

[23.12330961 -1.48124183  5.69922946]


In [24]:
#What's the value of the last element of w?

print('The value of the last element of w:',w[-1])

The value of the last element of w: 5.699229455065586
